In [1]:
import pickle
import numpy as np
import scipy.io as sio
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import datetime 
import seaborn
from stats import is_significant, _permutation_test
import xlsxwriter 
from scipy import stats
import xarray as xr
  
# Plot specifications
seaborn.set(context='talk')
seaborn.set_style("whitegrid", {'axes.grid': False})
plt.rc('axes', edgecolor='black')
plt.rc('axes', edgecolor='black')
plt.rcParams['axes.spines.right'] = False
plt.rcParams['axes.spines.top'] = False

ceil_name = '/om/user/msch/share/neural_nlp/identifier=Pereira2018-encoding.pkl'
score_name = '/om/user/msch/share/neural_nlp/benchmark=Pereira2018-encoding,model=gpt2-xl,subsample=None.pkl'

In [2]:
# Load score objects
with open(score_name, 'rb') as f:  
    result = pickle.load(f)

score = result['data']


In [3]:
from func import *

In [4]:
b=bestLangLayer(score)
o=meanSplitExp(score)
o1=freezeBestLangLayer(o,b)

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")


encoder.h.43


/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/xarray/core/nanops.py:159: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


In [7]:
o_lang=extractCoord(o1,'atlas','language')
o_md=extractCoord(o1,'atlas','MD')
o_dmn=extractCoord(o1,'atlas','DMN')


In [8]:
o_lang # There are 13517 lang neuroIDs across subjects

<xarray.Score (neuroid: 13517)>
array([0.314565, 0.31357 , 0.288955, ..., 0.38148 , 0.325691, 0.492467])
Coordinates:
    layer            <U12 'encoder.h.43'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '018' '018' '018' ... '018' '018' '018'
  - voxel_num        (neuroid) int64 28 29 31 32 38 42 ... 152 153 154 159 160
  - filter_strategy  (neuroid) object nan nan nan nan nan ... nan nan nan nan
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (neuroid) object 'LH_AntTemp' 'LH_AntTemp' ... 'LH_AntTemp'
  - indices_in_3d    (neuroid) int64 72505 72506 72584 ... 87754 87831 87832
  - col_to_coord_1   (neuroid) int64 62 63 62 63 63 63 63 ... 65 62 63 64 62 63
  - col_to_coord_2   (neuroid) int64 63 63 64 64 65 66 63 ... 65 66 66 66 67 67
  - col_to_coord_3   (neuroid) int64 10 10 10 10 10 10 11 ... 12 12 12 12 12 12
  - neuroid_id       (neuroid) object '018.28' '018.29' ... '018.159' '018.160'
  - at

In [9]:
o_md

<xarray.Score (neuroid: 29845)>
array([0.223181, 0.345573, 0.332533, ..., 0.220157, 0.272854, 0.426872])
Coordinates:
    layer            <U12 'encoder.h.43'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '018' '018' '018' ... '018' '018' '018'
  - voxel_num        (neuroid) int64 10170 10186 10187 ... 10307 10308 10315
  - filter_strategy  (neuroid) object 'HminusE' 'HminusE' ... 'HminusE'
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (neuroid) object 'RH_Precental_B_IFGop' ... 'LH_midFrontalOrb'
  - indices_in_3d    (neuroid) int64 252421 252629 252630 ... 254007 254041
  - col_to_coord_1   (neuroid) int64 16 66 67 12 13 14 68 ... 57 58 20 21 22 56
  - col_to_coord_2   (neuroid) int64 61 63 63 64 64 64 64 ... 80 80 81 81 81 81
  - col_to_coord_3   (neuroid) int64 34 34 34 34 34 34 34 ... 34 34 34 34 34 34
  - neuroid_id       (neuroid) object '018.10170' '018.10186' ... '018.10315'
  - atlas     

In [10]:
o_dmn

<xarray.Score (neuroid: 10948)>
array([0.415297, 0.363854, 0.452729, ..., 0.235367, 0.253682, 0.143237])
Coordinates:
    layer            <U12 'encoder.h.43'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '018' '018' '018' ... '018' '018' '018'
  - voxel_num        (neuroid) int64 166 167 269 270 271 ... 398 406 413 424 504
  - filter_strategy  (neuroid) object 'FIXminusH' 'FIXminusH' ... 'FIXminusH'
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (neuroid) object 'RH_FrontalMed' ... 'RH_FrontalMed'
  - indices_in_3d    (neuroid) int64 88282 88284 95708 ... 109406 109485 110559
  - col_to_coord_1   (neuroid) int64 39 41 39 41 39 41 39 ... 41 39 70 70 70 38
  - col_to_coord_2   (neuroid) int64 73 73 72 72 73 73 74 ... 75 76 54 55 56 70
  - col_to_coord_3   (neuroid) int64 12 12 13 13 13 13 13 ... 14 14 15 15 15 15
  - neuroid_id       (neuroid) object '018.166' '018.167' ... '018.504'
  - atlas       

In [12]:
# Drop NaNs
o_lang_nn = removeNaNs(o_lang)
o_lang_nn


["Number of NaNs: <xarray.DataArray ()>\narray(16)\nCoordinates:\n    layer    <U12 'encoder.h.43'subjID: 018"
 "Number of NaNs: <xarray.DataArray ()>\narray(16)\nCoordinates:\n    layer    <U12 'encoder.h.43'subjID: 018"
 "Number of NaNs: <xarray.DataArray ()>\narray(16)\nCoordinates:\n    layer    <U12 'encoder.h.43'subjID: 018"
 ...
 "Number of NaNs: <xarray.DataArray ()>\narray(16)\nCoordinates:\n    layer    <U12 'encoder.h.43'subjID: 296"
 "Number of NaNs: <xarray.DataArray ()>\narray(16)\nCoordinates:\n    layer    <U12 'encoder.h.43'subjID: 296"
 "Number of NaNs: <xarray.DataArray ()>\narray(16)\nCoordinates:\n    layer    <U12 'encoder.h.43'subjID: 296"]


<xarray.Score (neuroid: 13501)>
array([0.314565, 0.31357 , 0.288955, ..., 0.38148 , 0.325691, 0.492467])
Coordinates:
    layer            <U12 'encoder.h.43'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '018' '018' '018' ... '018' '018' '018'
  - voxel_num        (neuroid) int64 28 29 31 32 38 64 ... 192 193 199 207 211
  - filter_strategy  (neuroid) object nan nan nan nan nan ... nan nan nan nan
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (neuroid) object 'LH_AntTemp' 'LH_AntTemp' ... 'LH_AntTemp'
  - indices_in_3d    (neuroid) int64 72505 72506 72584 ... 94736 94815 94866
  - col_to_coord_1   (neuroid) int64 62 63 62 63 63 63 64 ... 16 15 16 15 15 66
  - col_to_coord_2   (neuroid) int64 63 63 64 64 65 63 63 ... 58 59 59 60 61 61
  - col_to_coord_3   (neuroid) int64 10 10 10 10 10 11 11 ... 13 13 13 13 13 13
  - neuroid_id       (neuroid) object '018.28' '018.29' ... '018.207' '018.211'
  - at

In [13]:
o_md_nn = removeNaNs(o_md)
o_md_nn

<xarray.Score (neuroid: 29845)>
array([0.223181, 0.345573, 0.332533, ..., 0.220157, 0.272854, 0.426872])
Coordinates:
    layer            <U12 'encoder.h.43'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '018' '018' '018' ... '018' '018' '018'
  - voxel_num        (neuroid) int64 10170 10186 10187 ... 10307 10308 10315
  - filter_strategy  (neuroid) object 'HminusE' 'HminusE' ... 'HminusE'
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (neuroid) object 'RH_Precental_B_IFGop' ... 'LH_midFrontalOrb'
  - indices_in_3d    (neuroid) int64 252421 252629 252630 ... 254007 254041
  - col_to_coord_1   (neuroid) int64 16 66 67 12 13 14 68 ... 57 58 20 21 22 56
  - col_to_coord_2   (neuroid) int64 61 63 63 64 64 64 64 ... 80 80 81 81 81 81
  - col_to_coord_3   (neuroid) int64 34 34 34 34 34 34 34 ... 34 34 34 34 34 34
  - neuroid_id       (neuroid) object '018.10170' '018.10186' ... '018.10315'
  - atlas     

In [14]:
o_dmn_nn = removeNaNs(o_dmn)
o_dmn_nn

<xarray.Score (neuroid: 10948)>
array([0.415297, 0.363854, 0.452729, ..., 0.235367, 0.253682, 0.143237])
Coordinates:
    layer            <U12 'encoder.h.43'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '018' '018' '018' ... '018' '018' '018'
  - voxel_num        (neuroid) int64 166 167 269 270 271 ... 398 406 413 424 504
  - filter_strategy  (neuroid) object 'FIXminusH' 'FIXminusH' ... 'FIXminusH'
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (neuroid) object 'RH_FrontalMed' ... 'RH_FrontalMed'
  - indices_in_3d    (neuroid) int64 88282 88284 95708 ... 109406 109485 110559
  - col_to_coord_1   (neuroid) int64 39 41 39 41 39 41 39 ... 41 39 70 70 70 38
  - col_to_coord_2   (neuroid) int64 73 73 72 72 73 73 74 ... 75 76 54 55 56 70
  - col_to_coord_3   (neuroid) int64 12 12 13 13 13 13 13 ... 14 14 15 15 15 15
  - neuroid_id       (neuroid) object '018.166' '018.167' ... '018.504'
  - atlas       