In [111]:
import pickle
import numpy as np
import scipy.io as sio
import matplotlib.pyplot as plt
import datetime 
import seaborn
import xlsxwriter 
import os

# ceil_name = '/om/user/msch/share/neural_nlp/identifier=Pereira2018-encoding.pkl'

# # Load ceil objects
# with open(ceil_name, 'rb') as f:  
#     resultc = pickle.load(f)

# ceil = resultc['data']

from func import *

models_l_pkl = []
models_nl_pkl = []

for path,dir,file in os.walk('/braintree/home/msch/.result_caching/neural_nlp.score/'):
    for fileNames in file:
        if fileNames.startswith("benchmark=Fedorenko2016v3-encoding"):
            if 'untrained' not in fileNames and 'random-embedding' not in fileNames:
                fileName = str(os.path.join(path,fileNames))
                print(fileName)
                models_l_pkl.append(fileName)
                
        if fileNames.startswith("benchmark=Fedorenko2016v3nonlang-encoding"):
            if 'untrained' not in fileNames:
                fileName = str(os.path.join(path,fileNames))
                print(fileName)
                models_nl_pkl.append(fileName)

/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-mlm-xnli15-1024,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=glove,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=albert-xlarge-v2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlm-mlm-en-2048,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=word2vec,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=distilgpt2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlnet-base-cased,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encod

In [112]:
len(models_l_pkl)

44

In [113]:
len(models_nl_pkl)

44

# Ceiled

In [117]:

comparison='Non-Language'
timestamp = '{:%Y-%m-%d}'.format(datetime.datetime.now())
workbook = xlsxwriter.Workbook('Fedorenko2016-Language-'+comparison+'-specificity-ceiled-'+timestamp+'.xlsx')

col=0

worksheet = workbook.add_worksheet("Language vs "+comparison) 
worksheet.write(0, col, 'Model_name')
worksheet.write(0, 1, 'Best_layer')
worksheet.write(0, 2, 'Comparison_1')
worksheet.write(0, 3, 'Comparison_2')
worksheet.write(0, 4, 'Normalized_Comparison1_Score')
worksheet.write(0, 5, 'Normalized_Comparison2_Score')
worksheet.write(0, 6, 'Median_Difference')
worksheet.write(0, 7, 'Median_Mult_Drop')    
worksheet.write(0, 8, 'Median_Perc_Drop')

for idx, model in enumerate(models_l_pkl):

    fname = models_l_pkl[idx]
    fname1 = fname.split('=')
    fname2 = fname1[-2].split(',')

    print(fname)
    fname_nl = '/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model='+fname2[0]+',subsample=None.pkl'
    print(fname_nl)

    with open(fname, 'rb') as f:  
        result = pickle.load(f)

    score_l = result['data']

    with open(fname_nl, 'rb') as f:  
        result_nl = pickle.load(f)

    score_nl = result_nl['data']
    
    diff, mult, perc, ceiled_lang, ceiled_comp, best_layer = computeDropFedorenko(score_l,score_nl,ceil=True)
 
    worksheet.write(idx+1, col, fname2[0]) 
    worksheet.write(idx+1, col + 1, str(best_layer)) 
    worksheet.write(idx+1, col + 2, 'Language') 
    worksheet.write(idx+1, col + 3, comparison) 
    worksheet.write(idx+1, col + 4, ceiled_lang) 
    worksheet.write(idx+1, col + 5, ceiled_comp) 
    worksheet.write(idx+1, col + 6, diff)
    worksheet.write(idx+1, col + 7, mult) 
    worksheet.write(idx+1, col + 8, perc) 

workbook.close()

/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-mlm-xnli15-1024,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlm-mlm-xnli15-1024,subsample=None.pkl
encoder.layer_norm2.9
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=glove,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=glove,subsample=None.pkl
projection
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=word2vec,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=word2vec,subsample=None.pkl
projection
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=distilgpt2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/be

embeddings
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=albert-xxlarge-v2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=albert-xxlarge-v2,subsample=None.pkl
embeddings
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=openaigpt,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=openaigpt,subsample=None.pkl
encoder.h.9.ln_2
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-mlm-en-2048,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlm-mlm-en-2048,subsample=None.pkl
encoder.layer_norm2.2
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=bert-large-uncased,subsample=None.pkl
/braintree/ho

# Not ceiled

In [137]:
comparison='Non-Language'
timestamp = '{:%Y-%m-%d}'.format(datetime.datetime.now())
workbook = xlsxwriter.Workbook('Fedorenko2016-Language-'+comparison+'-specificity-non-ceiled-'+timestamp+'.xlsx')

col=0

worksheet = workbook.add_worksheet("Language vs "+comparison) 
worksheet.write(0, col, 'Model_name')
worksheet.write(0, 1, 'Best_layer')
worksheet.write(0, 2, 'Comparison_1')
worksheet.write(0, 3, 'Comparison_2')
worksheet.write(0, 4, 'Predictivity_Comparison1')
worksheet.write(0, 5, 'Predictivity_Comparison2')
worksheet.write(0, 6, 'Median_Difference')
worksheet.write(0, 7, 'Median_Mult_Drop')    
worksheet.write(0, 8, 'Median_Perc_Drop')

for idx, model in enumerate(models_l_pkl):

    fname = models_l_pkl[idx]
    fname1 = fname.split('=')
    fname2 = fname1[-2].split(',')

    print(fname)
    fname_nl = '/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model='+fname2[0]+',subsample=None.pkl'
    print(fname_nl)

    with open(fname, 'rb') as f:  
        result = pickle.load(f)

    score_l = result['data']

    with open(fname_nl, 'rb') as f:  
        result_nl = pickle.load(f)

    score_nl = result_nl['data']
    
    diff, mult, perc, ceiled_lang, ceiled_comp, best_layer = computeDropFedorenko(score_l,score_nl,ceil=False)
 
    worksheet.write(idx+1, col, fname2[0]) 
    worksheet.write(idx+1, col + 1, str(best_layer)) 
    worksheet.write(idx+1, col + 2, 'Language') 
    worksheet.write(idx+1, col + 3, comparison) 
    worksheet.write(idx+1, col + 4, ceiled_lang) 
    worksheet.write(idx+1, col + 5, ceiled_comp) 
    worksheet.write(idx+1, col + 6, diff)
    worksheet.write(idx+1, col + 7, mult) 
    worksheet.write(idx+1, col + 8, perc) 

workbook.close()

/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-mlm-xnli15-1024,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlm-mlm-xnli15-1024,subsample=None.pkl
encoder.layer_norm2.9
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=glove,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=glove,subsample=None.pkl
projection
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=word2vec,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=word2vec,subsample=None.pkl
projection
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=distilgpt2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/be

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(

encoder.layer.18
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=gpt2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=gpt2,subsample=None.pkl
encoder.h.7
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=gpt2-large,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=gpt2-large,subsample=None.pkl
encoder.h.28
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=t5-3b,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=t5-3b,subsample=None.pkl
encoder.block.20
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=gpt2-medium,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fe

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(

/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-mlm-enfr-1024,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlm-mlm-enfr-1024,subsample=None.pkl
encoder.layer_norm2.5
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlnet-base-cased,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlnet-base-cased,subsample=None.pkl
encoder.layer.5
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=ctrl,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=ctrl,subsample=None.pkl
h.39
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=gpt2-xl,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.sc

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(

embeddings
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-mlm-100-1280,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlm-mlm-100-1280,subsample=None.pkl
encoder.layer_norm2.1
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-clm-enfr-1024,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlm-clm-enfr-1024,subsample=None.pkl
encoder.layer_norm2.5
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=bert-base-uncased,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=bert-base-uncased,subsample=None.pkl
encoder.layer.6.output
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-roberta-base

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(

encoder.block.9
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=albert-xlarge-v2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=albert-xlarge-v2,subsample=None.pkl
embeddings
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=albert-xxlarge-v2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=albert-xxlarge-v2,subsample=None.pkl
embeddings
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=openaigpt,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=openaigpt,subsample=None.pkl
encoder.h.9.ln_2
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-mlm-en-2048,subsample=None.pkl
/braintree/home/msch

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(


/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=ETM,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=ETM,subsample=None.pkl
projection
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=bert-large-uncased-whole-word-masking,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=bert-large-uncased-whole-word-masking,subsample=None.pkl
encoder.layer.9.output
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=skip-thoughts,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=skip-thoughts,subsample=None.pkl
encoder
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-roberta-large,subsample=None.pkl
/braintr

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(

In [125]:
ceil=False

In [136]:
def computeDropFedorenko(score_l,score_nl,ceil=True):
    b=bestLangLayer(score_l)
    if ceil:
        o_l=freezeBestLangLayer(score_l,b)
        o_comp=freezeBestLangLayer(score_nl,b) # freeze same layer
        center_lang=getCenter2(o_l).values
        center_comp=getCenter2(o_comp).values
    if not ceil:
        center_lang=freezeBestLangLayer(score_l.raw.raw,b).median()
        center_comp=freezeBestLangLayer(score_nl.raw.raw,b).median()

    diff = center_lang - center_comp
    mult = center_lang / center_comp
    perc = (diff / center_lang)*100

    return diff, mult, perc, center_lang, center_comp, b 

In [135]:
center_comp

<xarray.Score ()>
array(0.062184)
Coordinates:
    layer    <U21 'encoder.layer_norm2.9'

In [118]:
fname2

['lm_1b', 'subsample']

In [131]:
score_nl.raw.raw

<xarray.Score (layer: 13, neuroid: 105)>
array([[-0.016233,  0.031775, -0.008377, ..., -0.015614,  0.026776, -0.031975],
       [-0.034956, -0.001076, -0.010744, ...,  0.015962, -0.020611, -0.036501],
       [-0.029838,  0.007264, -0.008459, ..., -0.038711,  0.037876,  0.10451 ],
       ...,
       [ 0.106294, -0.000282,  0.109909, ...,  0.077617,  0.014321,  0.047541],
       [ 0.024337, -0.039717,  0.091405, ...,  0.001596, -0.050053,  0.022092],
       [ 0.049938,  0.070291,  0.116109, ...,  0.020643, -0.118665, -0.035648]])
Coordinates:
  * layer        (layer) object 'dropout' ... 'encoder.layer_norm2.11'
  * neuroid      (neuroid) MultiIndex
  - electrode    (neuroid) int64 0 1 2 3 4 5 6 7 8 ... 22 23 24 25 26 27 28 29
  - neuroid_id   (neuroid) int64 0 1 2 3 4 5 6 7 8 ... 22 23 24 25 26 27 28 29
  - subject_UID  (neuroid) int64 1 1 1 1 1 1 1 1 1 1 1 ... 1 1 1 1 1 1 2 2 2 2 2
Attributes:
    raw:      <xarray.Score (layer: 13, split: 5, neuroid: 105)>\narray([[[ 3...

In [120]:
score_nl

<xarray.Score (layer: 2, aggregation: 2)>
array([[-0.060489,  0.047108],
       [ 0.003018,  0.023531]])
Coordinates:
  * layer        (layer) object 'lstm/lstm_0/control_dependency' 'lstm/lstm_1/control_dependency'
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:          <xarray.Score (layer: 2, neuroid: 105)>\narray([[-7.978483e...
    description:  per-neuroid ceiling-normalized score
    ceiling:      <xarray.Score (aggregation: 3)>\narray([0.116164, 0.05213 ,...
    model:        lm_1b
    benchmark:    Fedorenko2016v3nonlang-encoding

# Sanity checking

In [25]:
np.shape(score.raw.values)

(13, 97)

In [40]:
score.raw

<xarray.Score (layer: 13, neuroid: 97)>
array([[ 0.068024, -0.335592, -0.11474 , ..., -0.088335, -0.397793,  0.138809],
       [ 0.028067, -0.046891, -0.233998, ..., -0.085894, -0.018869, -0.061208],
       [ 0.184944, -0.16922 ,  0.337123, ...,  0.01556 ,  0.275162, -0.162363],
       ...,
       [ 0.45498 ,  0.083965,  0.369752, ...,  0.597711,  0.648532,  0.352527],
       [ 0.347119,  0.378986,  0.381496, ...,  0.285543,  0.091092,  0.433191],
       [ 0.330438,  0.107857,  0.229053, ...,  0.690976,  0.834708, -0.188901]])
Coordinates:
  * layer        (layer) object 'dropout' ... 'encoder.layer_norm2.11'
  * neuroid      (neuroid) MultiIndex
  - electrode    (neuroid) int64 0 1 2 3 4 5 6 7 8 ... 22 23 24 25 26 27 28 29
  - neuroid_id   (neuroid) int64 0 1 2 3 4 5 6 7 8 ... 22 23 24 25 26 27 28 29
  - subject_UID  (neuroid) int64 1 1 1 1 1 1 1 1 1 1 1 ... 1 1 1 1 1 1 1 1 1 1 1
Attributes:
    raw:      <xarray.Score (layer: 13, neuroid: 97)>\narray([[ 0.018842, -0....
    ceiling: 

In [37]:
score.raw.ceiling

<xarray.Score (aggregation: 3, neuroid: 97)>
array([[0.276986, 0.255193, 0.450026, ..., 0.22299 , 0.158368, 0.378133],
       [0.127214, 0.148544, 0.133262, ..., 0.118591, 0.108438, 0.047434],
       [0.42316 , 0.429424, 0.387923, ..., 0.376741, 0.293212, 0.093101]])
Coordinates:
  * aggregation  (aggregation) <U10 'center' 'error_low' 'error_high'
  * neuroid      (neuroid) MultiIndex
  - neuroid_id   (neuroid) int64 0 1 2 3 4 5 6 7 8 ... 22 23 24 25 26 27 28 29
Attributes:
    raw:                  <xarray.Score (sub_subject_UID: 26, num_subjects: 4...
    bootstrapped_params:  <xarray.DataAssembly (bootstrap: 100, param: 2, neu...
    endpoint_x:           <xarray.DataAssembly (neuroid: 97)>\narray([ 20.,  ...

In [38]:
score.raw.ceiling[{'aggregation': [agg == 'center' for agg in score.raw.ceiling['aggregation'].values]}].squeeze('aggregation')

<xarray.Score (neuroid: 97)>
array([2.769856e-01, 2.551926e-01, 4.500265e-01, 3.868833e-01, 1.365794e-01,
       4.757289e-01, 1.716244e-01, 9.998963e-01, 4.487407e-02, 2.499845e-01,
       1.268732e-01, 8.054062e-05, 1.508040e-01, 4.210789e-01, 1.792784e-01,
       5.093611e-01, 1.357931e-05, 1.455410e-01, 2.785566e-01, 1.087995e-01,
       1.237404e-01, 1.656640e-01, 2.271788e-01, 3.987137e-01, 2.209538e-01,
       4.093732e-01, 3.131316e-01, 9.999843e-01, 3.560733e-01, 2.200534e-01,
       3.196259e-02, 1.432794e-01, 2.981981e-01, 6.614607e-02, 1.593810e-01,
       3.004410e-01, 2.035088e-01, 1.644961e-01, 1.523567e-01, 9.628072e-02,
       2.569274e-01, 7.887249e-02, 8.443256e-02, 1.732331e-02, 1.677446e-06,
       7.657057e-02, 7.880096e-02, 5.866428e-02, 1.249446e-01, 1.879526e-01,
       1.526759e-01, 1.793452e-07, 1.936113e-01, 9.998272e-01, 2.368586e-01,
       1.686485e-01, 1.677023e-01, 7.279055e-02, 2.154246e-01, 1.879795e-01,
       2.404010e-01, 2.482637e-01, 5.497518e-02

In [32]:
np.median(score.raw.values[0,:]) #legit, ceiled val

-0.08834780590844292

In [30]:
score.raw.raw

<xarray.Score (layer: 13, neuroid: 97)>
array([[ 0.018842, -0.085641, -0.051636, ..., -0.019698, -0.062998,  0.052488],
       [ 0.007774, -0.011966, -0.105305, ..., -0.019154, -0.002988, -0.023145],
       [ 0.051227, -0.043184,  0.151714, ...,  0.00347 ,  0.043577, -0.061395],
       ...,
       [ 0.126023,  0.021427,  0.166398, ...,  0.133284,  0.102707,  0.133302],
       [ 0.096147,  0.096715,  0.171683, ...,  0.063673,  0.014426,  0.163804],
       [ 0.091527,  0.027524,  0.10308 , ...,  0.154081,  0.132191, -0.07143 ]])
Coordinates:
  * layer        (layer) object 'dropout' ... 'encoder.layer_norm2.11'
  * neuroid      (neuroid) MultiIndex
  - electrode    (neuroid) int64 0 1 2 3 4 5 6 7 8 ... 22 23 24 25 26 27 28 29
  - neuroid_id   (neuroid) int64 0 1 2 3 4 5 6 7 8 ... 22 23 24 25 26 27 28 29
  - subject_UID  (neuroid) int64 1 1 1 1 1 1 1 1 1 1 1 ... 1 1 1 1 1 1 1 1 1 1 1
Attributes:
    raw:      <xarray.Score (layer: 13, split: 5, neuroid: 97)>\narray([[[ 0....

In [39]:
 0.018842/2.769856e-01 #legit, non-ceiled / ceiling

0.06802519697774903

In [42]:
freezeBestLangLayer(score.raw,b).median() #legit, ceiled

<xarray.Score ()>
array(0.491101)
Coordinates:
    layer    <U21 'encoder.layer_norm2.9'

In [43]:
freezeBestLangLayer(score.raw.raw,b).median() #legit, not ceiled

<xarray.Score ()>
array(0.0799)
Coordinates:
    layer    <U21 'encoder.layer_norm2.9'