In [1]:
import pickle
import numpy as np
import scipy.io as sio
import matplotlib.pyplot as plt
import datetime 
import seaborn
import xlsxwriter 
import os

from func import *

models_l_pkl = []
models_nl_pkl = []

for path,dir,file in os.walk('/braintree/home/msch/.result_caching/neural_nlp.score/'):
    for fileNames in file:
        if fileNames.startswith("benchmark=Fedorenko2016v3-encoding"):
            if 'untrained' not in fileNames and 'random-embedding' not in fileNames:
                fileName = str(os.path.join(path,fileNames))
                print(fileName)
                models_l_pkl.append(fileName)
                
        if fileNames.startswith("benchmark=Fedorenko2016v3nonlang-encoding"):
            if 'untrained' not in fileNames:
                fileName = str(os.path.join(path,fileNames))
                print(fileName)
                models_nl_pkl.append(fileName)

/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-mlm-xnli15-1024,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=glove,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=albert-xlarge-v2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlm-mlm-en-2048,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=word2vec,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=distilgpt2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlnet-base-cased,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encod

In [2]:
len(models_l_pkl)

44

In [3]:
len(models_nl_pkl)

44

# Ceiled

In [117]:

comparison='Non-Language'
timestamp = '{:%Y-%m-%d}'.format(datetime.datetime.now())
workbook = xlsxwriter.Workbook('Fedorenko2016-Language-'+comparison+'-specificity-ceiled-'+timestamp+'.xlsx')

col=0

worksheet = workbook.add_worksheet("Language vs "+comparison) 
worksheet.write(0, col, 'Model_name')
worksheet.write(0, 1, 'Best_layer')
worksheet.write(0, 2, 'Comparison_1')
worksheet.write(0, 3, 'Comparison_2')
worksheet.write(0, 4, 'Normalized_Comparison1_Score')
worksheet.write(0, 5, 'Normalized_Comparison2_Score')
worksheet.write(0, 6, 'Median_Difference')
worksheet.write(0, 7, 'Median_Mult_Drop')    
worksheet.write(0, 8, 'Median_Perc_Drop')

for idx, model in enumerate(models_l_pkl):

    fname = models_l_pkl[idx]
    fname1 = fname.split('=')
    fname2 = fname1[-2].split(',')

    print(fname)
    fname_nl = '/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model='+fname2[0]+',subsample=None.pkl'
    print(fname_nl)

    with open(fname, 'rb') as f:  
        result = pickle.load(f)

    score_l = result['data']

    with open(fname_nl, 'rb') as f:  
        result_nl = pickle.load(f)

    score_nl = result_nl['data']
    
    diff, mult, perc, ceiled_lang, ceiled_comp, best_layer = computeDropFedorenko(score_l,score_nl,ceil=True)
 
    worksheet.write(idx+1, col, fname2[0]) 
    worksheet.write(idx+1, col + 1, str(best_layer)) 
    worksheet.write(idx+1, col + 2, 'Language') 
    worksheet.write(idx+1, col + 3, comparison) 
    worksheet.write(idx+1, col + 4, ceiled_lang) 
    worksheet.write(idx+1, col + 5, ceiled_comp) 
    worksheet.write(idx+1, col + 6, diff)
    worksheet.write(idx+1, col + 7, mult) 
    worksheet.write(idx+1, col + 8, perc) 

workbook.close()

/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-mlm-xnli15-1024,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlm-mlm-xnli15-1024,subsample=None.pkl
encoder.layer_norm2.9
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=glove,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=glove,subsample=None.pkl
projection
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=word2vec,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=word2vec,subsample=None.pkl
projection
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=distilgpt2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/be

embeddings
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=albert-xxlarge-v2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=albert-xxlarge-v2,subsample=None.pkl
embeddings
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=openaigpt,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=openaigpt,subsample=None.pkl
encoder.h.9.ln_2
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-mlm-en-2048,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlm-mlm-en-2048,subsample=None.pkl
encoder.layer_norm2.2
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=bert-large-uncased,subsample=None.pkl
/braintree/ho

# Not ceiled - reran 21062020

In [4]:
comparison='Non-Language'
timestamp = '{:%Y-%m-%d}'.format(datetime.datetime.now())
workbook = xlsxwriter.Workbook('Fedorenko2016-Language-'+comparison+'-specificity-non-ceiled-'+timestamp+'.xlsx')

col=0

worksheet = workbook.add_worksheet("Language vs "+comparison) 
worksheet.write(0, col, 'Model_name')
worksheet.write(0, 1, 'Best_layer')
worksheet.write(0, 2, 'Comparison_1')
worksheet.write(0, 3, 'Comparison_2')
worksheet.write(0, 4, 'Predictivity_Comparison1')
worksheet.write(0, 5, 'Predictivity_Comparison2')
worksheet.write(0, 6, 'Median_Difference')
worksheet.write(0, 7, 'Median_Mult_Drop')    
worksheet.write(0, 8, 'Median_Perc_Drop')

for idx, model in enumerate(models_l_pkl):

    fname = models_l_pkl[idx]
    fname1 = fname.split('=')
    fname2 = fname1[-2].split(',')

    print(fname)
    fname_nl = '/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model='+fname2[0]+',subsample=None.pkl'
    print(fname_nl)

    with open(fname, 'rb') as f:  
        result = pickle.load(f)

    score_l = result['data']

    with open(fname_nl, 'rb') as f:  
        result_nl = pickle.load(f)

    score_nl = result_nl['data']
    
    diff, mult, perc, ceiled_lang, ceiled_comp, best_layer = computeDropFedorenko(score_l,score_nl,ceil=False)
 
    worksheet.write(idx+1, col, fname2[0]) 
    worksheet.write(idx+1, col + 1, str(best_layer)) 
    worksheet.write(idx+1, col + 2, 'Language') 
    worksheet.write(idx+1, col + 3, comparison) 
    worksheet.write(idx+1, col + 4, ceiled_lang) 
    worksheet.write(idx+1, col + 5, ceiled_comp) 
    worksheet.write(idx+1, col + 6, diff)
    worksheet.write(idx+1, col + 7, mult) 
    worksheet.write(idx+1, col + 8, perc) 

workbook.close()

/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-mlm-xnli15-1024,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlm-mlm-xnli15-1024,subsample=None.pkl


/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(

encoder.layer_norm2.9
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=glove,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=glove,subsample=None.pkl
projection
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=word2vec,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=word2vec,subsample=None.pkl
projection
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=distilgpt2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=distilgpt2,subsample=None.pkl
encoder.h.2
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=albert-xxlarge-v1,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/b

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(

embeddings
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=albert-large-v1,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=albert-large-v1,subsample=None.pkl
embeddings
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=roberta-large,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=roberta-large,subsample=None.pkl
encoder.layer.18
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=gpt2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=gpt2,subsample=None.pkl
encoder.h.7
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=gpt2-large,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.s

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(

encoder.h.28
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=t5-3b,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=t5-3b,subsample=None.pkl
encoder.block.20
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=gpt2-medium,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=gpt2-medium,subsample=None.pkl
encoder.h.14
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=albert-base-v2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=albert-base-v2,subsample=None.pkl
embeddings
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=t5-11b,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(

/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=ctrl,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=ctrl,subsample=None.pkl
h.39
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=gpt2-xl,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=gpt2-xl,subsample=None.pkl
encoder.h.17
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=distilbert-base-uncased,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=distilbert-base-uncased,subsample=None.pkl
transformer.layer.4
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=bert-base-multilingual-cased,subsample=None.pkl
/braintree/home/msch/.result_caching/neu

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(

/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=albert-large-v2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=albert-large-v2,subsample=None.pkl
embeddings
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=albert-xlarge-v1,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=albert-xlarge-v1,subsample=None.pkl
embeddings
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-mlm-100-1280,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlm-mlm-100-1280,subsample=None.pkl
encoder.layer_norm2.1
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-clm-enfr-1024,subsample=None.pkl
/braintree/home/msc

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(

/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=bert-base-uncased,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=bert-base-uncased,subsample=None.pkl
encoder.layer.6.output
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-roberta-base,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlm-roberta-base,subsample=None.pkl
encoder.layer.4
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=t5-large,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=t5-large,subsample=None.pkl
encoder.block.21
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=albert-base-v1,subsample=None.pkl
/braintree/home/msch/.

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(

/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlnet-large-cased,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlnet-large-cased,subsample=None.pkl
encoder.layer.23
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=t5-base,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=t5-base,subsample=None.pkl
encoder.block.9
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=albert-xlarge-v2,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=albert-xlarge-v2,subsample=None.pkl
embeddings
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=albert-xxlarge-v2,subsample=None.pkl
/braintree/home/msch/.result_cach

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(

/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=openaigpt,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=openaigpt,subsample=None.pkl
encoder.h.9.ln_2
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-mlm-en-2048,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlm-mlm-en-2048,subsample=None.pkl
encoder.layer_norm2.2
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=bert-large-uncased,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=bert-large-uncased,subsample=None.pkl
encoder.layer.12.output
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=transfo-xl-wt103,subsample=None.pkl
/braintree/

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(

/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=t5-small,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=t5-small,subsample=None.pkl
encoder.block.0
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=transformer,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=transformer,subsample=None.pkl
encoder.transformer.5.feed_forward.layer_norm
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=ETM,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=ETM,subsample=None.pkl
projection
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=bert-large-uncased-whole-word-masking,subsample=None.pkl
/braintree/home/msch

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(

/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=skip-thoughts,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=skip-thoughts,subsample=None.pkl
encoder
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=xlm-roberta-large,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=xlm-roberta-large,subsample=None.pkl
encoder.layer.14
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=roberta-base,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=roberta-base,subsample=None.pkl
encoder.layer.11
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=lm_1b,subsample=None.pkl
/braintree/home/msch/.result_caching/neural

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(

In [125]:
# ceil=False

In [136]:
# def computeDropFedorenko(score_l,score_nl,ceil=True):
#     b=bestLangLayer(score_l)
#     if ceil:
#         o_l=freezeBestLangLayer(score_l,b)
#         o_comp=freezeBestLangLayer(score_nl,b) # freeze same layer
#         center_lang=getCenter2(o_l).values
#         center_comp=getCenter2(o_comp).values
#     if not ceil:
#         center_lang=freezeBestLangLayer(score_l.raw.raw,b).median()
#         center_comp=freezeBestLangLayer(score_nl.raw.raw,b).median()

#     diff = center_lang - center_comp
#     mult = center_lang / center_comp
#     perc = (diff / center_lang)*100

#     return diff, mult, perc, center_lang, center_comp, b 

In [131]:
score_nl.raw.raw

<xarray.Score (layer: 13, neuroid: 105)>
array([[-0.016233,  0.031775, -0.008377, ..., -0.015614,  0.026776, -0.031975],
       [-0.034956, -0.001076, -0.010744, ...,  0.015962, -0.020611, -0.036501],
       [-0.029838,  0.007264, -0.008459, ..., -0.038711,  0.037876,  0.10451 ],
       ...,
       [ 0.106294, -0.000282,  0.109909, ...,  0.077617,  0.014321,  0.047541],
       [ 0.024337, -0.039717,  0.091405, ...,  0.001596, -0.050053,  0.022092],
       [ 0.049938,  0.070291,  0.116109, ...,  0.020643, -0.118665, -0.035648]])
Coordinates:
  * layer        (layer) object 'dropout' ... 'encoder.layer_norm2.11'
  * neuroid      (neuroid) MultiIndex
  - electrode    (neuroid) int64 0 1 2 3 4 5 6 7 8 ... 22 23 24 25 26 27 28 29
  - neuroid_id   (neuroid) int64 0 1 2 3 4 5 6 7 8 ... 22 23 24 25 26 27 28 29
  - subject_UID  (neuroid) int64 1 1 1 1 1 1 1 1 1 1 1 ... 1 1 1 1 1 1 2 2 2 2 2
Attributes:
    raw:      <xarray.Score (layer: 13, split: 5, neuroid: 105)>\narray([[[ 3...

In [120]:
score_nl

<xarray.Score (layer: 2, aggregation: 2)>
array([[-0.060489,  0.047108],
       [ 0.003018,  0.023531]])
Coordinates:
  * layer        (layer) object 'lstm/lstm_0/control_dependency' 'lstm/lstm_1/control_dependency'
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:          <xarray.Score (layer: 2, neuroid: 105)>\narray([[-7.978483e...
    description:  per-neuroid ceiling-normalized score
    ceiling:      <xarray.Score (aggregation: 3)>\narray([0.116164, 0.05213 ,...
    model:        lm_1b
    benchmark:    Fedorenko2016v3nonlang-encoding

# Sanity checking - 1. Ceiled analyses

In [7]:
# For checking, pick out the last model that is iterated through:

print(models_l_pkl[-1])

/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=lm_1b,subsample=None.pkl


In [8]:
fname = models_l_pkl[-1]
fname1 = fname.split('=')
fname2 = fname1[-2].split(',')

print(fname)
fname_nl = '/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model='+fname2[0]+',subsample=None.pkl'
print(fname_nl)

/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3-encoding,model=lm_1b,subsample=None.pkl
/braintree/home/msch/.result_caching/neural_nlp.score/benchmark=Fedorenko2016v3nonlang-encoding,model=lm_1b,subsample=None.pkl


In [9]:
with open(fname, 'rb') as f:  
    result = pickle.load(f)

score_l = result['data']

with open(fname_nl, 'rb') as f:  
    result_nl = pickle.load(f)

score_nl = result_nl['data']



In [10]:
score_l

<xarray.Score (layer: 2, aggregation: 2)>
array([[-0.018091,  0.020521],
       [ 0.047135,  0.030416]])
Coordinates:
  * layer        (layer) object 'lstm/lstm_0/control_dependency' 'lstm/lstm_1/control_dependency'
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:          <xarray.Score (layer: 2, neuroid: 97)>\narray([[-1.486838e-...
    description:  per-neuroid ceiling-normalized score
    ceiling:      <xarray.Score (aggregation: 3)>\narray([0.168649, 0.052784,...
    model:        lm_1b
    benchmark:    Fedorenko2016v3-encoding

In [11]:
b=bestLangLayer(score_l)
print(b)

lstm/lstm_1/control_dependency
lstm/lstm_1/control_dependency


/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")


In [12]:
# Below code is from the function, if ceil = True
# if ceil:
o_l=freezeBestLangLayer(score_l,b)
o_comp=freezeBestLangLayer(score_nl,b) # freeze same layer

In [13]:
o_l # For lang electrodes

<xarray.Score (aggregation: 2)>
array([0.047135, 0.030416])
Coordinates:
    layer        <U30 'lstm/lstm_1/control_dependency'
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:          <xarray.Score (neuroid: 97)>\narray([ 4.129890e-01,  5.2144...
    description:  per-neuroid ceiling-normalized score
    ceiling:      <xarray.Score (aggregation: 3)>\narray([0.168649, 0.052784,...
    model:        lm_1b
    benchmark:    Fedorenko2016v3-encoding

In [11]:
center_lang=getCenter2(o_l).values # Get center score.
print(center_lang)

0.04713465259316591


In [12]:
# For non-lang
o_comp # same layer extracted.

<xarray.Score (aggregation: 2)>
array([0.003018, 0.023531])
Coordinates:
    layer        <U30 'lstm/lstm_1/control_dependency'
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:          <xarray.Score (neuroid: 105)>\narray([ 2.028383e+05, -7.971...
    description:  per-neuroid ceiling-normalized score
    ceiling:      <xarray.Score (aggregation: 3)>\narray([0.116164, 0.05213 ,...
    model:        lm_1b
    benchmark:    Fedorenko2016v3nonlang-encoding

In [14]:
center_comp=getCenter2(o_comp).values
print(center_comp)

0.0030184169555057642


In [16]:
# Difference should thus be: 
o_l-o_comp

<xarray.Score (aggregation: 2)>
array([0.044116, 0.006886])
Coordinates:
    layer        <U30 'lstm/lstm_1/control_dependency'
  * aggregation  (aggregation) <U6 'center' 'error'

In [18]:
# Checking with the function:
diff, mult, perc, ceiled_lang, ceiled_comp, best_layer = computeDropFedorenko(score_l,score_nl,ceil=True)
print(diff) # Corresponds. Also to the excel sheet: Fedorenko2016-Language-Non-Language-specificity-ceiled-2020-06-03.xlsx

lstm/lstm_1/control_dependency
0.04411623563766015


In [25]:
# Investigate ceiling
score_l

<xarray.Score (layer: 2, aggregation: 2)>
array([[-0.018091,  0.020521],
       [ 0.047135,  0.030416]])
Coordinates:
  * layer        (layer) object 'lstm/lstm_0/control_dependency' 'lstm/lstm_1/control_dependency'
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:          <xarray.Score (layer: 2, neuroid: 97)>\narray([[-1.486838e-...
    description:  per-neuroid ceiling-normalized score
    ceiling:      <xarray.Score (aggregation: 3)>\narray([0.168649, 0.052784,...
    model:        lm_1b
    benchmark:    Fedorenko2016v3-encoding

In [30]:
o_l.raw.groupby('subject_UID').median().median() # The median score arises from median across subjects, then median again.

<xarray.Score ()>
array(0.047135)
Coordinates:
    layer    <U30 'lstm/lstm_1/control_dependency'

In [14]:
# Find median for not ceiled:
o_l.raw.raw.groupby('subject_UID').median().median()


<xarray.Score ()>
array(0.013898)
Coordinates:
    layer    <U30 'lstm/lstm_1/control_dependency'

In [15]:
# In prev analyses, I did:
o_l.raw.raw.median()
# Matches the one in: Fedorenko2016-Language-Non-Language-specificity-non-ceiled-2020-06-03 (wrong)

<xarray.Score ()>
array(0.013252)
Coordinates:
    layer    <U30 'lstm/lstm_1/control_dependency'

In [35]:
# How was the ceiling computed? 
o_l_center_ceil = getCenter2(o_l.raw.ceiling)
o_l_center_ceil

<xarray.Score (neuroid: 97)>
array([2.769856e-01, 2.551926e-01, 4.500265e-01, 3.868833e-01, 1.365794e-01,
       4.757289e-01, 1.716244e-01, 9.998963e-01, 4.487407e-02, 2.499845e-01,
       1.268732e-01, 8.054062e-05, 1.508040e-01, 4.210789e-01, 1.792784e-01,
       5.093611e-01, 1.357931e-05, 1.455410e-01, 2.785566e-01, 1.087995e-01,
       1.237404e-01, 1.656640e-01, 2.271788e-01, 3.987137e-01, 2.209538e-01,
       4.093732e-01, 3.131316e-01, 9.999843e-01, 3.560733e-01, 2.200534e-01,
       3.196259e-02, 1.432794e-01, 2.981981e-01, 6.614607e-02, 1.593810e-01,
       3.004410e-01, 2.035088e-01, 1.644961e-01, 1.523567e-01, 9.628072e-02,
       2.569274e-01, 7.887249e-02, 8.443256e-02, 1.732331e-02, 1.677446e-06,
       7.657057e-02, 7.880096e-02, 5.866428e-02, 1.249446e-01, 1.879526e-01,
       1.526759e-01, 1.793452e-07, 1.936113e-01, 9.998272e-01, 2.368586e-01,
       1.686485e-01, 1.677023e-01, 7.279055e-02, 2.154246e-01, 1.879795e-01,
       2.404010e-01, 2.482637e-01, 5.497518e-02

In [43]:
o_l.raw.ceiling

<xarray.Score (aggregation: 3, neuroid: 97)>
array([[0.276986, 0.255193, 0.450026, ..., 0.22299 , 0.158368, 0.378133],
       [0.127214, 0.148544, 0.133262, ..., 0.118591, 0.108438, 0.047434],
       [0.42316 , 0.429424, 0.387923, ..., 0.376741, 0.293212, 0.093101]])
Coordinates:
  * aggregation  (aggregation) <U10 'center' 'error_low' 'error_high'
  * neuroid      (neuroid) MultiIndex
  - neuroid_id   (neuroid) int64 0 1 2 3 4 5 6 7 8 ... 22 23 24 25 26 27 28 29
Attributes:
    raw:                  <xarray.Score (sub_subject_UID: 26, num_subjects: 4...
    bootstrapped_params:  <xarray.DataAssembly (bootstrap: 100, param: 2, neu...
    endpoint_x:           <xarray.DataAssembly (neuroid: 97)>\narray([ 20.,  ...

In [45]:
o_l_center_ceil.median() # Median ceiling

<xarray.Score ()>
array(0.168649)
Coordinates:
    aggregation  <U10 'center'

In [47]:
score_l.ceiling # Median ceiling - however, note that this median ceiling was not used to obtain the score.
# This was done per electrode (see below)

<xarray.Score (aggregation: 3)>
array([0.168649, 0.052784, 0.134393])
Coordinates:
  * aggregation  (aggregation) <U10 'center' 'error_low' 'error_high'
Attributes:
    bootstrapped_params:  <xarray.DataAssembly (bootstrap: 100, param: 2)>\na...
    endpoint_x:           <xarray.DataAssembly ()>\narray(9.)
    raw:                  <xarray.Score (aggregation: 3, neuroid: 97)>\narray...

In [48]:
score_l.ceiling.raw

<xarray.Score (aggregation: 3, neuroid: 97)>
array([[0.276986, 0.255193, 0.450026, ..., 0.22299 , 0.158368, 0.378133],
       [0.127214, 0.148544, 0.133262, ..., 0.118591, 0.108438, 0.047434],
       [0.42316 , 0.429424, 0.387923, ..., 0.376741, 0.293212, 0.093101]])
Coordinates:
  * aggregation  (aggregation) <U10 'center' 'error_low' 'error_high'
  * neuroid      (neuroid) MultiIndex
  - neuroid_id   (neuroid) int64 0 1 2 3 4 5 6 7 8 ... 22 23 24 25 26 27 28 29
Attributes:
    raw:                  <xarray.Score (sub_subject_UID: 26, num_subjects: 4...
    bootstrapped_params:  <xarray.DataAssembly (bootstrap: 100, param: 2, neu...
    endpoint_x:           <xarray.DataAssembly (neuroid: 97)>\narray([ 20.,  ...

In [52]:
o_l.raw

<xarray.Score (neuroid: 97)>
array([ 4.129890e-01,  5.214422e-01,  9.554386e-02,  1.394123e-01,
       -4.837559e-01,  1.070129e-02,  7.080731e-02, -7.612255e-03,
        5.477528e-01,  5.301158e-02,  7.774736e-02,  5.114603e+02,
       -2.213132e-01, -6.648754e-02, -2.486181e-01,  2.262733e-01,
       -2.966059e+03, -2.982561e-01,  1.363789e-01, -8.758201e-01,
        2.786114e-01, -2.063734e-01,  3.289014e-01,  1.098549e-01,
        1.752363e-01, -3.205963e-02,  3.579033e-02,  3.157911e-02,
       -3.035445e-02, -3.927964e-01,  1.937184e+00,  1.584248e-01,
        1.368624e-01,  8.411252e-01, -3.671141e-01,  5.522539e-02,
       -1.732314e-01,  5.934568e-02,  8.850665e-02, -2.751957e-01,
        6.660591e-02,  3.354598e-02,  4.909535e-01, -2.192130e+00,
        3.703543e+04,  4.774235e-01, -6.460502e-02,  1.063878e+00,
        5.307447e-01,  1.487609e-01,  3.305875e-01,  3.885843e+05,
        1.858505e-02, -7.532788e-03,  9.360864e-02, -1.550372e-02,
       -2.474501e-01, -9.099362e-

In [53]:
o_l.raw.raw # Not normalized scores.

<xarray.Score (neuroid: 97)>
array([ 0.114392,  0.133068,  0.042997,  0.053936, -0.066071,  0.005091,
        0.012152, -0.007611,  0.02458 ,  0.013252,  0.009864,  0.041193,
       -0.033375, -0.027997, -0.044572,  0.115255, -0.040277, -0.043408,
        0.037989, -0.095289,  0.034475, -0.034189,  0.074719,  0.043801,
        0.038719, -0.013124,  0.011207,  0.031579, -0.010808, -0.086436,
        0.061917,  0.022699,  0.040812,  0.055637, -0.058511,  0.016592,
       -0.035254,  0.009762,  0.013485, -0.026496,  0.017113,  0.002646,
        0.041452, -0.037975,  0.062125,  0.036557, -0.005091,  0.062412,
        0.066314,  0.02796 ,  0.050473,  0.069691,  0.003598, -0.007531,
        0.022172, -0.002615, -0.041498, -0.066235, -0.060903,  0.010155,
       -0.026272,  0.018588,  0.066618, -0.019179,  0.097953,  0.089893,
        0.064193,  0.106272, -0.031639,  0.035776,  0.008204,  0.02446 ,
       -0.007684, -0.070245, -0.009469, -0.097676, -0.078867,  0.014912,
        0.013898, -0.0

In [54]:
0.114392/0.276986 # Gives the first value, i.e. for electrode 1.
# This is the not ceiled score, divided by the ceiling. Both for electrode 1.

0.412988382084293

In [58]:
# Divide all normalized scores by their ceiling:
# All not ceiled vals divided by ceiling, per electrode:
manual_ceiled = o_l.raw.raw/o_l_center_ceil.values
manual_ceiled

<xarray.Score (neuroid: 97)>
array([ 4.129890e-01,  5.214422e-01,  9.554386e-02,  1.394123e-01,
       -4.837559e-01,  1.070129e-02,  7.080731e-02, -7.612255e-03,
        5.477528e-01,  5.301158e-02,  7.774736e-02,  5.114603e+02,
       -2.213132e-01, -6.648754e-02, -2.486181e-01,  2.262733e-01,
       -2.966059e+03, -2.982561e-01,  1.363789e-01, -8.758201e-01,
        2.786114e-01, -2.063734e-01,  3.289014e-01,  1.098549e-01,
        1.752363e-01, -3.205963e-02,  3.579033e-02,  3.157911e-02,
       -3.035445e-02, -3.927964e-01,  1.937184e+00,  1.584248e-01,
        1.368624e-01,  8.411252e-01, -3.671141e-01,  5.522539e-02,
       -1.732314e-01,  5.934568e-02,  8.850665e-02, -2.751957e-01,
        6.660591e-02,  3.354598e-02,  4.909535e-01, -2.192130e+00,
        3.703543e+04,  4.774235e-01, -6.460502e-02,  1.063878e+00,
        5.307447e-01,  1.487609e-01,  3.305875e-01,  3.885843e+05,
        1.858505e-02, -7.532788e-03,  9.360864e-02, -1.550372e-02,
       -2.474501e-01, -9.099362e-

In [61]:
manual_ceiled.groupby('subject_UID').median().median()

<xarray.Score ()>
array(0.047135)
Coordinates:
    layer    <U30 'lstm/lstm_1/control_dependency'

In [ ]:
# Thus, the ECoG data was normalized per-electrode. Then median across subs, then median again.

### Checking whether this also holds true for the non-lang assembly.

In [62]:
o_comp # Overall score - the one used for analyses.

<xarray.Score (aggregation: 2)>
array([0.003018, 0.023531])
Coordinates:
    layer        <U30 'lstm/lstm_1/control_dependency'
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:          <xarray.Score (neuroid: 105)>\narray([ 2.028383e+05, -7.971...
    description:  per-neuroid ceiling-normalized score
    ceiling:      <xarray.Score (aggregation: 3)>\narray([0.116164, 0.05213 ,...
    model:        lm_1b
    benchmark:    Fedorenko2016v3nonlang-encoding

In [63]:
# Get center ceiling values:
o_comp_center_ceil = getCenter2(o_comp.raw.ceiling)
o_comp_center_ceil

<xarray.Score (neuroid: 105)>
array([1.448933e-07, 5.212969e-02, 9.635411e-02, 4.839803e-08, 9.990403e-01,
       1.551109e-01, 4.671731e-02, 6.648999e-02, 4.411571e-01, 4.250366e-02,
       1.949580e-01, 5.954338e-02, 9.997326e-01, 9.999873e-01, 8.251841e-02,
       2.128950e-01, 1.645926e-01, 3.944148e-01, 9.915946e-02, 1.507927e-01,
       1.573497e-01, 1.229716e-01, 8.502359e-02, 1.404781e-01, 4.407586e-08,
       1.085917e-01, 2.246840e-01, 3.040161e-01, 1.933836e-01, 9.976442e-01,
       1.077222e-01, 5.264769e-01, 1.161641e-01, 9.987514e-01, 3.278715e-01,
       2.680098e-02, 2.848121e-01, 1.859232e-01, 9.999476e-01, 4.764583e-02,
       7.792652e-02, 3.652808e-02, 9.933857e-08, 1.056405e-01, 2.642320e-02,
       1.330423e-09, 9.999736e-01, 1.782986e-02, 4.198945e-02, 4.718160e-02,
       1.853546e-08, 5.646617e-09, 1.067096e-06, 7.481936e-08, 8.295233e-02,
       9.628907e-09, 9.994804e-01, 1.388746e-01, 4.136222e-06, 1.962669e-09,
       9.918041e-10, 9.888310e-01, 1.782349e-0

In [64]:
# Get raw values:
o_comp.raw.raw

<xarray.Score (neuroid: 105)>
array([ 2.938991e-02, -4.155691e-02,  6.308131e-02, -2.554944e-02,
        6.745820e-02,  4.159275e-02,  3.040040e-02, -1.056268e-02,
        1.544086e-02,  4.958228e-02,  1.547964e-01, -9.721864e-02,
        1.659298e-02, -7.855656e-02, -3.575510e-02, -1.159213e-02,
       -3.304446e-02,  8.564529e-05,  5.387235e-02,  2.165194e-02,
       -7.804589e-02,  9.447160e-02, -2.388053e-02, -3.482680e-02,
       -3.525356e-02, -4.633790e-02, -1.018333e-01, -1.344557e-02,
       -5.272226e-02,  3.886134e-02,  3.043477e-03,  7.715291e-02,
       -1.759912e-03,  3.387968e-02,  4.716172e-02, -9.718474e-02,
        3.520585e-02, -4.439626e-02, -6.673006e-02,  1.843675e-02,
        1.576181e-01, -8.346981e-03, -6.181820e-02,  5.078812e-02,
        4.102869e-02,  4.269619e-02, -2.197833e-03, -9.374865e-02,
       -7.704697e-02,  1.191005e-02, -1.467647e-01, -1.036329e-01,
       -1.025818e-01, -6.906747e-02, -1.010563e-01, -1.737336e-01,
        1.063392e-02,  3.769011e

In [66]:
# Normalize:
manual_o_comp_ceiled = o_comp.raw.raw/o_comp_center_ceil.values
manual_o_comp_ceiled

<xarray.Score (neuroid: 105)>
array([ 2.028383e+05, -7.971831e-01,  6.546820e-01, -5.279024e+05,
        6.752300e-02,  2.681485e-01,  6.507309e-01, -1.588612e-01,
        3.500081e-02,  1.166541e+00,  7.939986e-01, -1.632736e+00,
        1.659742e-02, -7.855756e-02, -4.332984e-01, -5.444999e-02,
       -2.007652e-01,  2.171452e-04,  5.432900e-01,  1.435874e-01,
       -4.960028e-01,  7.682389e-01, -2.808695e-01, -2.479162e-01,
       -7.998382e+05, -4.267166e-01, -4.532291e-01, -4.422652e-02,
       -2.726304e-01,  3.895311e-02,  2.825302e-02,  1.465457e-01,
       -1.515022e-02,  3.392203e-02,  1.438421e-01, -3.626164e+00,
        1.236108e-01, -2.387882e-01, -6.673356e-02,  3.869542e-01,
        2.022651e+00, -2.285086e-01, -6.222980e+05,  4.807635e-01,
        1.552753e+00,  3.209220e+07, -2.197891e-03, -5.257956e+00,
       -1.834913e+00,  2.524299e-01, -7.918047e+06, -1.835309e+07,
       -9.613175e+04, -9.231230e+05, -1.218246e+00, -1.804292e+07,
        1.063944e-02,  2.713968e

In [67]:
manual_o_comp_ceiled.groupby('subject_UID').median().median() # Corresponds. Also corresponds to Martins:
# scores-Fedorenko2016v3nonlang-encoding-normalized

<xarray.Score ()>
array(0.003018)
Coordinates:
    layer    <U30 'lstm/lstm_1/control_dependency'

## Older sanity checking - based on xlm-mlm-xnli15-1024

In [25]:
np.shape(score.raw.values)

(13, 97)

In [40]:
score.raw

<xarray.Score (layer: 13, neuroid: 97)>
array([[ 0.068024, -0.335592, -0.11474 , ..., -0.088335, -0.397793,  0.138809],
       [ 0.028067, -0.046891, -0.233998, ..., -0.085894, -0.018869, -0.061208],
       [ 0.184944, -0.16922 ,  0.337123, ...,  0.01556 ,  0.275162, -0.162363],
       ...,
       [ 0.45498 ,  0.083965,  0.369752, ...,  0.597711,  0.648532,  0.352527],
       [ 0.347119,  0.378986,  0.381496, ...,  0.285543,  0.091092,  0.433191],
       [ 0.330438,  0.107857,  0.229053, ...,  0.690976,  0.834708, -0.188901]])
Coordinates:
  * layer        (layer) object 'dropout' ... 'encoder.layer_norm2.11'
  * neuroid      (neuroid) MultiIndex
  - electrode    (neuroid) int64 0 1 2 3 4 5 6 7 8 ... 22 23 24 25 26 27 28 29
  - neuroid_id   (neuroid) int64 0 1 2 3 4 5 6 7 8 ... 22 23 24 25 26 27 28 29
  - subject_UID  (neuroid) int64 1 1 1 1 1 1 1 1 1 1 1 ... 1 1 1 1 1 1 1 1 1 1 1
Attributes:
    raw:      <xarray.Score (layer: 13, neuroid: 97)>\narray([[ 0.018842, -0....
    ceiling: 

In [37]:
score.raw.ceiling

<xarray.Score (aggregation: 3, neuroid: 97)>
array([[0.276986, 0.255193, 0.450026, ..., 0.22299 , 0.158368, 0.378133],
       [0.127214, 0.148544, 0.133262, ..., 0.118591, 0.108438, 0.047434],
       [0.42316 , 0.429424, 0.387923, ..., 0.376741, 0.293212, 0.093101]])
Coordinates:
  * aggregation  (aggregation) <U10 'center' 'error_low' 'error_high'
  * neuroid      (neuroid) MultiIndex
  - neuroid_id   (neuroid) int64 0 1 2 3 4 5 6 7 8 ... 22 23 24 25 26 27 28 29
Attributes:
    raw:                  <xarray.Score (sub_subject_UID: 26, num_subjects: 4...
    bootstrapped_params:  <xarray.DataAssembly (bootstrap: 100, param: 2, neu...
    endpoint_x:           <xarray.DataAssembly (neuroid: 97)>\narray([ 20.,  ...

In [38]:
score.raw.ceiling[{'aggregation': [agg == 'center' for agg in score.raw.ceiling['aggregation'].values]}].squeeze('aggregation')

<xarray.Score (neuroid: 97)>
array([2.769856e-01, 2.551926e-01, 4.500265e-01, 3.868833e-01, 1.365794e-01,
       4.757289e-01, 1.716244e-01, 9.998963e-01, 4.487407e-02, 2.499845e-01,
       1.268732e-01, 8.054062e-05, 1.508040e-01, 4.210789e-01, 1.792784e-01,
       5.093611e-01, 1.357931e-05, 1.455410e-01, 2.785566e-01, 1.087995e-01,
       1.237404e-01, 1.656640e-01, 2.271788e-01, 3.987137e-01, 2.209538e-01,
       4.093732e-01, 3.131316e-01, 9.999843e-01, 3.560733e-01, 2.200534e-01,
       3.196259e-02, 1.432794e-01, 2.981981e-01, 6.614607e-02, 1.593810e-01,
       3.004410e-01, 2.035088e-01, 1.644961e-01, 1.523567e-01, 9.628072e-02,
       2.569274e-01, 7.887249e-02, 8.443256e-02, 1.732331e-02, 1.677446e-06,
       7.657057e-02, 7.880096e-02, 5.866428e-02, 1.249446e-01, 1.879526e-01,
       1.526759e-01, 1.793452e-07, 1.936113e-01, 9.998272e-01, 2.368586e-01,
       1.686485e-01, 1.677023e-01, 7.279055e-02, 2.154246e-01, 1.879795e-01,
       2.404010e-01, 2.482637e-01, 5.497518e-02

In [32]:
np.median(score.raw.values[0,:]) #legit, ceiled val

-0.08834780590844292

In [30]:
score.raw.raw

<xarray.Score (layer: 13, neuroid: 97)>
array([[ 0.018842, -0.085641, -0.051636, ..., -0.019698, -0.062998,  0.052488],
       [ 0.007774, -0.011966, -0.105305, ..., -0.019154, -0.002988, -0.023145],
       [ 0.051227, -0.043184,  0.151714, ...,  0.00347 ,  0.043577, -0.061395],
       ...,
       [ 0.126023,  0.021427,  0.166398, ...,  0.133284,  0.102707,  0.133302],
       [ 0.096147,  0.096715,  0.171683, ...,  0.063673,  0.014426,  0.163804],
       [ 0.091527,  0.027524,  0.10308 , ...,  0.154081,  0.132191, -0.07143 ]])
Coordinates:
  * layer        (layer) object 'dropout' ... 'encoder.layer_norm2.11'
  * neuroid      (neuroid) MultiIndex
  - electrode    (neuroid) int64 0 1 2 3 4 5 6 7 8 ... 22 23 24 25 26 27 28 29
  - neuroid_id   (neuroid) int64 0 1 2 3 4 5 6 7 8 ... 22 23 24 25 26 27 28 29
  - subject_UID  (neuroid) int64 1 1 1 1 1 1 1 1 1 1 1 ... 1 1 1 1 1 1 1 1 1 1 1
Attributes:
    raw:      <xarray.Score (layer: 13, split: 5, neuroid: 97)>\narray([[[ 0....

In [39]:
 0.018842/2.769856e-01 #legit, non-ceiled / ceiling

0.06802519697774903

In [42]:
freezeBestLangLayer(score.raw,b).median() #legit, ceiled

<xarray.Score ()>
array(0.491101)
Coordinates:
    layer    <U21 'encoder.layer_norm2.9'

In [43]:
freezeBestLangLayer(score.raw.raw,b).median() #legit, not ceiled

<xarray.Score ()>
array(0.0799)
Coordinates:
    layer    <U21 'encoder.layer_norm2.9'