In [4]:
import pickle
import numpy as np
import scipy.io as sio
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import datetime 
import seaborn
from stats import is_significant, _permutation_test
import xlsxwriter 
from scipy import stats
import xarray as xr
  
# Plot specifications
seaborn.set(context='talk')
seaborn.set_style("whitegrid", {'axes.grid': False})
plt.rc('axes', edgecolor='black')
plt.rc('axes', edgecolor='black')
plt.rcParams['axes.spines.right'] = False
plt.rcParams['axes.spines.top'] = False

ceil_name = '/om/user/msch/share/neural_nlp/identifier=Pereira2018-encoding.pkl'
score_name = '/om/user/msch/share/neural_nlp/benchmark=Pereira2018-encoding,model=gpt2-xl,subsample=None.pkl'

In [5]:
# Load score objects
with open(score_name, 'rb') as f:  
    result = pickle.load(f)

score = result['data']

# Load ceil objects
with open(ceil_name, 'rb') as f:  
    resultc = pickle.load(f)

ceil = resultc['data']

In [6]:
from func import *

In [98]:
models_pkl = []
for path,dir,file in os.walk('/braintree/home/msch/.result_caching/neural_nlp.score/'):
    for fileNames in file:
        if fileNames.startswith("benchmark=Pereira2018-encoding"):
            if 'untrained' not in fileNames:
                fileName = str(os.path.join(path,fileNames))
                models_pkl.append(fileName)

In [99]:
len(models_pkl)

46

In [111]:
comparison='MD'
timestamp = '{:%Y-%m-%d}'.format(datetime.datetime.now())
workbook = xlsxwriter.Workbook('Pereira2018-lang-specificy-'+timestamp+'.xlsx')

col=0

worksheet = workbook.add_worksheet("Language vs "+comparison) 
worksheet.write(0, col, 'Model_name')
worksheet.write(0, 1, 'Best_layer')
worksheet.write(0, 2, 'Comparison_1')
worksheet.write(0, 3, 'Comparison_2')
worksheet.write(0, 4, 'Normalized_Comparison1_Score')
worksheet.write(0, 5, 'Normalized_Comparison2_Score')
worksheet.write(0, 6, 'Median_Difference')
worksheet.write(0, 7, 'Median_Mult_Drop')    
worksheet.write(0, 8, 'Median_Perc_Drop')

for idx, model in enumerate(models_pkl):

    fname = models_pkl[idx]
    fname1= fname.split('=')
    fname2=fname1[-2].split(',')
    
    with open(fname, 'rb') as f:  
        result = pickle.load(f)

    score = result['data']
    
    diff, mult, perc, ceiled_lang, ceiled_comp, best_layer = computeDrop(score,ceil,comparison)
 
    worksheet.write(idx+1, col, fname2[0]) 
    worksheet.write(idx+1, col + 1, str(best_layer)) 
    worksheet.write(idx+1, col + 2, 'Language') 
    worksheet.write(idx+1, col + 3, comparison) 
    worksheet.write(idx+1, col + 4, ceiled_lang) 
    worksheet.write(idx+1, col + 5, ceiled_comp) 
    worksheet.write(idx+1, col + 6, diff)
    worksheet.write(idx+1, col + 7, mult) 
    worksheet.write(idx+1, col + 8, perc) 

workbook.close()
    


/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")


h.46


/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/xarray/core/nanops.py:159: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: IndexError('Boolean array size 50628 is used to index array with shape (50647,).',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.cond

encoder.layer_norm2.5


/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: IndexError('Boolean array size 50628 is used to index array with shape (50647,).',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")


In [109]:
fname2

['ctrl', 'subsample']

In [5]:

    # Ceiling
c=getCenter(ceil)
c_lang=extractCoord(c,'atlas','language')#.median()
c_lang

<xarray.Score (neuroid: 6723)>
array([0.510463, 0.488328, 0.550399, ..., 0.276792, 0.275839, 0.266383])
Coordinates:
    aggregation      <U10 'center'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '289' '289' '289' ... '289' '289' '289'
  - voxel_num        (neuroid) int64 73 80 81 91 139 140 ... 375 503 504 512 513
  - filter_strategy  (neuroid) object nan nan nan nan nan ... nan nan nan nan
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (neuroid) object 'LH_AntTemp' 'LH_AntTemp' ... 'RH_AntTemp'
  - indices_in_3d    (neuroid) int64 79933 80012 80013 ... 109667 109745 109746
  - col_to_coord_1   (neuroid) int64 64 64 65 65 64 65 64 ... 15 65 14 15 14 15
  - col_to_coord_2   (neuroid) int64 62 63 63 64 62 62 63 ... 61 62 59 59 60 60
  - col_to_coord_3   (neuroid) int64 11 11 11 11 12 12 12 ... 14 14 15 15 15 15
  - neuroid_id       (neuroid) object '289.73' '289.80' ... '289.512' '289.513'
  - atla

In [6]:
ceilang=aggregateScores(c_lang)
ceilang

<xarray.Score ()>
array(0.318567)
Coordinates:
    aggregation  <U10 'center'

In [7]:
extractCoord(c,'atlas','language').median()

<xarray.Score ()>
array(0.309608)
Coordinates:
    aggregation  <U10 'center'

In [28]:
c2=c.groupby('atlas').median()

In [49]:
c2.values[[x == 'language' for x in c2['atlas'].values]]

array([0.3096079])

In [8]:
def computeDrop(score,ceil,comparison):
    b=bestLangLayer(score)
    o=meanSplitExp(score)
    o1=freezeBestLangLayer(o,b)
    o_lang=extractCoord(o1,'atlas','language')
    o_comp=extractCoord(o1,'atlas',comparison)

    center_lang=aggregateScores(o_lang)
    center_comp=aggregateScores(o_comp)

    # Ceiling
    c=getCenter(ceil)
    c_lang=extractCoord(c,'atlas','language')#.median()
    c_comp=extractCoord(c,'atlas',comparison)#.median()
    
    ceil_lang=aggregateScores(c_lang)
    ceil_comp=aggregateScores(c_comp)

    ceiled_lang = center_lang/ceil_lang
    ceiled_comp = center_comp/ceil_comp

    diff = ceiled_lang - ceiled_comp
    #print(f"median drop {np.nanmedian(diffs)}+-{np.std(diffs)}")
    mult = ceiled_lang / ceiled_comp
    #print(f"median multiplicative drop {np.nanmedian(mults)}+-{np.std(mults)}")
    perc = diff / ceiled_lang

    return diff, mult, perc, ceiled_lang, ceiled_comp, b 

In [9]:
diff, mult, perc, ceiled_lang, ceiled_comp, b=computeDrop(score,ceil,'MD')

encoder.h.43


/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/xarray/core/nanops.py:159: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


In [10]:
computeDrop(score,ceil,'MD')

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")


encoder.h.43


/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/xarray/core/nanops.py:159: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: IndexError('Boolean array size 50628 is used to index array with shape (50647,).',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")


(<xarray.Score ()>
 array(-0.182367)
 Coordinates:
     layer        <U12 'encoder.h.43'
     aggregation  <U10 'center', <xarray.Score ()>
 array(0.851344)
 Coordinates:
     layer        <U12 'encoder.h.43'
     aggregation  <U10 'center', <xarray.Score ()>
 array(-0.174613)
 Coordinates:
     layer        <U12 'encoder.h.43'
     aggregation  <U10 'center', <xarray.Score ()>
 array(1.044403)
 Coordinates:
     layer        <U12 'encoder.h.43'
     aggregation  <U10 'center', <xarray.Score ()>
 array(1.226769)
 Coordinates:
     layer        <U12 'encoder.h.43'
     aggregation  <U10 'center', array('encoder.h.43', dtype='<U12'))

## Sanity checking the entire pipeline and function used.

#### Using the loaded GPT2-xl and ceiling to check. The function used is as follows:

In [7]:
def computeDrop(score,ceil,comparison):
    b=bestLangLayer(score)
    o=meanSplitExp(score)
    o1=freezeBestLangLayer(o,b)
    o_lang=extractCoord(o1,'atlas','language')
    o_comp=extractCoord(o1,'atlas',comparison)

    center_lang=aggregateScores(o_lang)
    center_comp=aggregateScores(o_comp)

    # Ceiling
    c=getCenter(ceil)
#    c_lang=extractCoord(c,'atlas','language').median()
#    c_comp=extractCoord(c,'atlas',comparison).median()

#    ceiled_lang = center_lang/c_lang
#    ceiled_comp = center_comp/c_comp

    c_lang=extractCoord(c,'atlas','language')#.median()
    c_comp=extractCoord(c,'atlas',comparison)#.median()
    
    ceil_lang=aggregateScores(c_lang)
    ceil_comp=aggregateScores(c_comp)

    ceiled_lang = center_lang/ceil_lang
    ceiled_comp = center_comp/ceil_comp

    diff = ceiled_lang - ceiled_comp
    mult = ceiled_lang / ceiled_comp
    perc = diff / ceiled_lang

    return diff, mult, perc, ceiled_lang, ceiled_comp, b 

## For the scores:

In [8]:
# Going through every single step:
b=bestLangLayer(score)
o=meanSplitExp(score)
o1=freezeBestLangLayer(o,b)
o1 # Meaned across split and exp, best layer extracted.


/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")


encoder.h.43


/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/xarray/core/nanops.py:159: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


<xarray.Score (neuroid: 102880)>
array([0.314565, 0.31357 , 0.288955, ..., 0.220157, 0.272854, 0.426872])
Coordinates:
    layer            <U12 'encoder.h.43'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '018' '018' '018' ... '018' '018' '018'
  - voxel_num        (neuroid) int64 28 29 31 32 38 42 ... 152 153 154 159 160
  - filter_strategy  (neuroid) object nan nan nan nan nan ... nan nan nan nan
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (neuroid) object 'LH_AntTemp' 'LH_AntTemp' ... 'LH_AntTemp'
  - indices_in_3d    (neuroid) int64 72505 72506 72584 ... 87754 87831 87832
  - col_to_coord_1   (neuroid) int64 62 63 62 63 63 63 63 ... 65 62 63 64 62 63
  - col_to_coord_2   (neuroid) int64 63 63 64 64 65 66 63 ... 65 66 66 66 67 67
  - col_to_coord_3   (neuroid) int64 10 10 10 10 10 10 11 ... 12 12 12 12 12 12
  - neuroid_id       (neuroid) object '018.28' '018.29' ... '018.159' '018.160'
  - a

In [9]:
# Extracting the network:
comparison='MD'
o_lang=extractCoord(o1,'atlas','language')
o_comp=extractCoord(o1,'atlas',comparison)
o_lang

<xarray.Score (neuroid: 13517)>
array([0.314565, 0.31357 , 0.288955, ..., 0.38148 , 0.325691, 0.492467])
Coordinates:
    layer            <U12 'encoder.h.43'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '018' '018' '018' ... '018' '018' '018'
  - voxel_num        (neuroid) int64 28 29 31 32 38 42 ... 152 153 154 159 160
  - filter_strategy  (neuroid) object nan nan nan nan nan ... nan nan nan nan
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (neuroid) object 'LH_AntTemp' 'LH_AntTemp' ... 'LH_AntTemp'
  - indices_in_3d    (neuroid) int64 72505 72506 72584 ... 87754 87831 87832
  - col_to_coord_1   (neuroid) int64 62 63 62 63 63 63 63 ... 65 62 63 64 62 63
  - col_to_coord_2   (neuroid) int64 63 63 64 64 65 66 63 ... 65 66 66 66 67 67
  - col_to_coord_3   (neuroid) int64 10 10 10 10 10 10 11 ... 12 12 12 12 12 12
  - neuroid_id       (neuroid) object '018.28' '018.29' ... '018.159' '018.160'
  - at

In [10]:
o_comp #scores for MD 

<xarray.Score (neuroid: 29845)>
array([0.223181, 0.345573, 0.332533, ..., 0.220157, 0.272854, 0.426872])
Coordinates:
    layer            <U12 'encoder.h.43'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '018' '018' '018' ... '018' '018' '018'
  - voxel_num        (neuroid) int64 10170 10186 10187 ... 10307 10308 10315
  - filter_strategy  (neuroid) object 'HminusE' 'HminusE' ... 'HminusE'
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (neuroid) object 'RH_Precental_B_IFGop' ... 'LH_midFrontalOrb'
  - indices_in_3d    (neuroid) int64 252421 252629 252630 ... 254007 254041
  - col_to_coord_1   (neuroid) int64 16 66 67 12 13 14 68 ... 57 58 20 21 22 56
  - col_to_coord_2   (neuroid) int64 61 63 63 64 64 64 64 ... 80 80 81 81 81 81
  - col_to_coord_3   (neuroid) int64 34 34 34 34 34 34 34 ... 34 34 34 34 34 34
  - neuroid_id       (neuroid) object '018.10170' '018.10186' ... '018.10315'
  - atlas     

In [11]:
# Aggregate across subjects, median across subjects, and then median again. Identical to msch's function.
center_lang=aggregateScores(o_lang)
center_comp=aggregateScores(o_comp)

In [12]:
center_lang # checked with Martin during a meeting, he had identical value. And see below - the normalized score also matches with msch.

<xarray.Score ()>
array(0.332712)
Coordinates:
    layer    <U12 'encoder.h.43'

In [13]:
center_comp

<xarray.Score ()>
array(0.304799)
Coordinates:
    layer    <U12 'encoder.h.43'

## For the ceiling

In [14]:
ceil.raw # All computed ceiling values

<xarray.Score (neuroid: 50628, aggregation: 3)>
array([[0.510463, 0.013919, 0.01341 ],
       [0.488328, 0.011905, 0.014889],
       [0.550399, 0.010395, 0.008968],
       ...,
       [0.375212, 0.080541, 0.215047],
       [0.36408 , 0.057842, 0.174951],
       [0.360292, 0.026817, 0.042612]])
Coordinates:
  * aggregation      (aggregation) <U10 'center' 'error_low' 'error_high'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '289' '289' '289' ... '289' '289' '289'
  - voxel_num        (neuroid) int64 73 80 81 91 139 140 ... 363 364 365 375 411
  - filter_strategy  (neuroid) object nan nan nan nan ... nan nan 'FIXminusH'
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (neuroid) object 'LH_AntTemp' ... 'RH_FrontalMed'
  - indices_in_3d    (neuroid) int64 79933 80012 80013 ... 102320 102449 103291
  - col_to_coord_1   (neuroid) int64 64 64 65 65 64 65 64 ... 16 13 14 15 65 38
  - col_to_coord_2   (neuroi

In [15]:
c=getCenter(ceil) # Get the center values from above.
c

<xarray.Score (neuroid: 50628)>
array([0.510463, 0.488328, 0.550399, ..., 0.375212, 0.36408 , 0.360292])
Coordinates:
    aggregation      <U10 'center'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '289' '289' '289' ... '289' '289' '289'
  - voxel_num        (neuroid) int64 73 80 81 91 139 140 ... 363 364 365 375 411
  - filter_strategy  (neuroid) object nan nan nan nan ... nan nan 'FIXminusH'
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (neuroid) object 'LH_AntTemp' ... 'RH_FrontalMed'
  - indices_in_3d    (neuroid) int64 79933 80012 80013 ... 102320 102449 103291
  - col_to_coord_1   (neuroid) int64 64 64 65 65 64 65 64 ... 16 13 14 15 65 38
  - col_to_coord_2   (neuroid) int64 62 63 63 64 62 62 63 ... 60 61 61 61 62 73
  - col_to_coord_3   (neuroid) int64 11 11 11 11 12 12 12 ... 14 14 14 14 14 14
  - neuroid_id       (neuroid) object '289.73' '289.80' ... '289.375' '289.411'
  - atlas        

In [16]:
# Extract the atlas of interest
c_lang=extractCoord(c,'atlas','language')
c_comp=extractCoord(c,'atlas',comparison)
c_lang

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: IndexError('Boolean array size 50628 is used to index array with shape (50647,).',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")


<xarray.Score (neuroid: 6723)>
array([0.510463, 0.488328, 0.550399, ..., 0.276792, 0.275839, 0.266383])
Coordinates:
    aggregation      <U10 'center'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '289' '289' '289' ... '289' '289' '289'
  - voxel_num        (neuroid) int64 73 80 81 91 139 140 ... 375 503 504 512 513
  - filter_strategy  (neuroid) object nan nan nan nan nan ... nan nan nan nan
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (neuroid) object 'LH_AntTemp' 'LH_AntTemp' ... 'RH_AntTemp'
  - indices_in_3d    (neuroid) int64 79933 80012 80013 ... 109667 109745 109746
  - col_to_coord_1   (neuroid) int64 64 64 65 65 64 65 64 ... 15 65 14 15 14 15
  - col_to_coord_2   (neuroid) int64 62 63 63 64 62 62 63 ... 61 62 59 59 60 60
  - col_to_coord_3   (neuroid) int64 11 11 11 11 12 12 12 ... 14 14 15 15 15 15
  - neuroid_id       (neuroid) object '289.73' '289.80' ... '289.512' '289.513'
  - atla

In [17]:
c_comp


<xarray.Score (neuroid: 14667)>
array([0.30579 , 0.309311, 0.30106 , ..., 0.293943, 0.289287, 0.360292])
Coordinates:
    aggregation      <U10 'center'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '289' '289' '289' ... '289' '289' '289'
  - voxel_num        (neuroid) int64 10001 10007 10008 ... 10841 10859 10860
  - filter_strategy  (neuroid) object 'HminusE' 'HminusE' ... 'HminusE'
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (neuroid) object 'LH_midFrontal' ... 'RH_midFrontalOrb'
  - indices_in_3d    (neuroid) int64 238802 238912 238913 ... 246933 246982
  - col_to_coord_1   (neuroid) int64 64 16 17 28 28 28 56 ... 28 28 28 28 58 28
  - col_to_coord_2   (neuroid) int64 78 80 80 83 84 85 87 ... 83 84 85 86 86 87
  - col_to_coord_3   (neuroid) int64 32 32 32 32 32 32 32 ... 33 33 33 33 33 33
  - neuroid_id       (neuroid) object '289.10001' '289.10007' ... '289.10860'
  - atlas            (neuro

In [18]:
# Aggregate the scores by computing median over subjects, and median again.
ceil_lang=aggregateScores(c_lang)
ceil_comp=aggregateScores(c_comp)
ceil_lang

<xarray.Score ()>
array(0.318567)
Coordinates:
    aggregation  <U10 'center'

In [19]:
ceil_comp

<xarray.Score ()>
array(0.248457)
Coordinates:
    aggregation  <U10 'center'

In [20]:
# Compute ceiled value:
ceiled_lang = center_lang/ceil_lang
ceiled_comp = center_comp/ceil_comp

In [21]:
ceiled_lang

<xarray.Score ()>
array(1.044403)
Coordinates:
    layer        <U12 'encoder.h.43'
    aggregation  <U10 'center'

In [22]:
ceiled_comp # Both of these scores match with msch's scores and my scores in the excel:
# Pereira2018-lang-MD-specificity-2020-05-19.xlsx

<xarray.Score ()>
array(1.226769)
Coordinates:
    layer        <U12 'encoder.h.43'
    aggregation  <U10 'center'

In [23]:
# The diff should thus be: 
1.044403-1.226769 #matches with the excel.

-0.18236600000000003

In [25]:
# Test the function:
diff, mult, perc, ceiled_lang, ceiled_comp, b = computeDrop(score,ceil,comparison)
print(diff) # matches.

/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: ValueError("dimensions ['aggregation'] do not exist",)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: squeeze on raw values failed: KeyError('aggregation',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")


encoder.h.43


/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/xarray/core/nanops.py:159: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)
/om/user/gretatu/.conda/envs/brainmodeling/lib/python3.6/site-packages/brainscore/metrics/__init__.py:48: UserWarning: isel on raw values failed: IndexError('Boolean array size 50628 is used to index array with shape (50647,).',)
  warnings.warn(f"{operation} on raw values failed: {repr(e)}")


<xarray.Score ()>
array(-0.182367)
Coordinates:
    layer        <U12 'encoder.h.43'
    aggregation  <U10 'center'


### For non-ceiled analyses, the identical thing happens, just without the division with the ceiling.